### ISSUE TITLE
Function for snake case?

### ISSUE THREAD

**Issue by haruyuki7121994** [makejavas/EasyCode#102]
Hi guys,
I'm having problem handling snake case in plugin, can you provide function or way to handle sanke case?

Example:
Model: NewTest
Snake case: new_test

**Comment by makejavas** [comment]
java code example:
`System.out.println("NewTest".replaceAll("[A-Z]", "_$0").toLowerCase().replaceFirst("^_", ""))`
velocity code example:
`$tableInfo.name.replaceAll("[A-Z]", "_$0").toLowerCase().replaceFirst("^_", "")`

**Comment by haruyuki7121994** [comment]
I solved the problem.
Thanks for the great plugin!
