### ISSUE TITLE
支持自动生成go的struct

### ISSUE THREAD

**Issue by tlightsky** [makejavas/EasyCode#12]
```go
type Person struct {
    FirstName  string `db:"first_name"`
    LastName   string `db:"last_name"`
    MiddleName string `db:"middle_name,omitempty"`
}
```

**Comment by makejavas** [comment]
不是很明白你想表达什么

**Comment by caizm** [comment]
你好。请问平时都是在哪里学习插件开发到知识的，可以分享一下

**Comment by makejavas** [comment]
看官方文档



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "caizm"<notifications@github.com&gt;; 
发送时间: 2019年11月30日(星期六) 凌晨0:51
收件人: "makejavas/EasyCode"<EasyCode@noreply.github.com&gt;; 
抄送: "makejava"<1353036300@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [makejavas/EasyCode] 支持自动生成go的struct (#12)




你好。请问平时都是在哪里学习插件开发到知识的，可以分享一下
