### ISSUE TITLE
can not install webstorm

### ISSUE THREAD

**Issue by HarkTu** [makejavas/EasyCode#16]
there is no plugin velocity in webstorm. any suggestion?

![easi](https://user-images.githubusercontent.com/46054251/70993486-ccd6b480-20d4-11ea-8e78-1d81ab36f361.jpg)

**Comment by makejavas** [comment]
You can try to extract Velocity plugin&nbsp;to webstorm&nbsp;from idea，Or use idea directly。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shtiliyan Karamfilov"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上7:56
收件人:&nbsp;"makejavas/EasyCode"<EasyCode@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[makejavas/EasyCode] can not install webstorm (#16)




there is no plugin velocity in webstorm. any suggestion?
