### ISSUE TITLE
表的字段定义成 bigint(20) unsigned 提示识别不了这个类型

### ISSUE THREAD

**Issue by bee06** [makejavas/EasyCode#24]
表的字段定义成 bigint(20) unsigned 提示识别不了这个类型 
![截屏2020-03-19下午12 28 24](https://user-images.githubusercontent.com/2787429/77031667-408ea300-69dd-11ea-8f2b-0c53b433e6f3.png)

**Comment by makejavas** [comment]
bigint\(20\) unsigned
要写全
