### ISSUE TITLE
模板导出为文件

### ISSUE THREAD

**Issue by HQ1228234037** [makejavas/EasyCode#29]
能不能加个模板导出为文件的功能，装2020版的时候没想到这个，把旧版数据全清了，然后自己写了半天的模板都没了

**Comment by makejavas** [comment]
[教程路径](https://gitee.com/makejava/EasyCode/wikis/7.%E6%80%8E%E4%B9%88%E5%B0%86%E9%85%8D%E7%BD%AE%E5%AF%BC%E5%87%BA%E5%88%B0%E6%9C%AC%E5%9C%B0%EF%BC%9F?sort_id=725174)
