### ISSUE TITLE
全局配置init去掉表前缀不生效

### ISSUE THREAD

**Issue by mumu121** [makejavas/EasyCode#31]
Template Setting 用的MybatisPlus,生成代码时，表的前缀没有生效，全局init去前缀代码如下：
##去掉表的t_前缀
$!tableInfo.setName($tool.getClassName($tableInfo.obj.name.replaceFirst("t_","")))

**Comment by makejavas** [comment]
[#11 ](https://github.com/makejavas/EasyCode/issues/11)
