### ISSUE TITLE
模板导出可否添加自定义

### ISSUE THREAD

**Issue by zxiaozhou** [makejavas/EasyCode#34]
模板导出可否支持自定义服务器或导出为文件，导入你的服务器保存时间太短了。我觉得可以把导出上传你服务器的数据存为json或xml。虽然idea支持导出设置，，但全局的太麻烦，，还有这个也有点问题：那就是如果开启了自动同步没法导出到本地

**Comment by makejavas** [comment]
计划会改为永久保存，不过业余时间并不多。可能周期会比较长，因为并不是简单的改为永久保存。还会有一系列的东西一起出来。

**Comment by fosin** [comment]
我遇到一次模版丢失的事件，这个功能太需要了。

**Comment by makejavas** [comment]
新版本已经提供多种导出方式，暂时关闭问题。
