### ISSUE TITLE
是否支持生成的代码在不同目录下

### ISSUE THREAD

**Issue by JoonJune** [makejavas/EasyCode#35]
因为项目中, 涉及三个项目, api / rpc接口协议包 / service, 所以是否可以支持生成的代码在不同目录下

**Comment by makejavas** [comment]
支持，使用
&nbsp; &nbsp; 回调
&nbsp; &nbsp; &amp;callback 回调对象
&nbsp; &nbsp; &nbsp; &nbsp; setFileName(String) 设置文件储存名字
&nbsp; &nbsp; &nbsp; &nbsp; setSavePath(String) 设置文件储存路径，默认使用选中路径
&nbsp; &nbsp; &nbsp; &nbsp; setReformat(Boolean) 设置是否重新格式化生成后的代码，默认为true
