### ISSUE TITLE
Generate Code的界面，能不能填写Model的名称而不直接用表名

### ISSUE THREAD

**Issue by rchlz** [makejavas/EasyCode#36]
经常我们在设计数据库时，会在数据库的表名加很多前缀，比如xxx_common_uploadfile。而我们在生成代码时只想生成名为UploadFile的Model及其Mapper、Service，但是现在根据数据库的表名就会生成XxxCommonUploadfile的类

**Comment by rchlz** [comment]
发现pr10是为了解决这个问题的

**Comment by makejavas** [comment]
PR已经合并处理，[查看内测版](http://www.shujuhaiyang.com/)
