### ISSUE TITLE
IDEA2020.1 mapper.xml生成不了 MAC系统

### ISSUE THREAD

**Issue by messi-gao** [makejavas/EasyCode#38]
IDEA2020.1 mapper.xml生成不了，其他java文件正常

**Comment by makejavas** [comment]
是否有报错信息？

**Comment by messi-gao** [comment]
无任何报错信息

**Comment by makejavas** [comment]
IDEA右下角是否有红点存在

**Comment by messi-gao** [comment]
没有

**Comment by makejavas** [comment]
好的，我先看看

**Comment by messi-gao** [comment]
非常感谢

**Comment by makejavas** [comment]
我这边测试是可以生成的，默认的生成位置是在resources/mapper中，你仔细找找是否真的没生成。

**Comment by messi-gao** [comment]
我确认了好几次 确实没有生成 你这边需要什么日志啥的能定位问题吗

**Comment by makejavas** [comment]
但是你并没有产生报错日志

**Comment by messi-gao** [comment]
我去看看源码 debug下吧

**Comment by makejavas** [comment]
你可以试试实时调试，能否生成mapper.xml

**Comment by messi-gao** [comment]
实时调试怎么用

**Comment by messi-gao** [comment]
https://gitee.com/makejava/EasyCode/wikis/pages?sort_id=725187&doc_id=166248 这个图片打不开了

**Comment by makejavas** [comment]
[点击查看](https://gitee.com/makejava/EasyCode/wikis/1.%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8debug?sort_id=725187)

**Comment by messi-gao** [comment]
试了下 实时调试是好用的

**Comment by makejavas** [comment]
那么问题应该就出在文件保存，可能是没有写权限导致写入文件失败。

**Comment by messi-gao** [comment]
好奇怪 java文件写入没问题 mapper有问题

**Comment by makejavas** [comment]
试试1.2.4RC版本是否能够解决你的问题

**Comment by messi-gao** [comment]
好的 电脑没带 周一去公司试下

**Comment by messi-gao** [comment]
刚刚试了下 还是不行

**Comment by makejavas** [comment]
请升级至最新版解决，暂时先关闭问题。如问题仍然存在请重新打开。
