### ISSUE TITLE
文件名设置不生效的bug

### ISSUE THREAD

**Issue by x-chuiao** [makejavas/EasyCode#39]
您好
我在模板中修改了文件名为TableInfo.obj.name,但是最终文件名仍为TableInfo.name
我的版本:1.2.3
附:
建议所有文件名的设置使用已定义的save宏,目前只在eneity中使用

**Comment by makejavas** [comment]
@x-chuiao 如需使用save宏，在模板头部引入宏定义即可。具体参考entity模板顶部的引入。

**Comment by x-chuiao** [comment]
感谢您的回复,问题已得到解决,文件名已经能像预期设置的那样了,不知道是否是设置未生效的问题.
另外还有一个问题,当包被重名命后,且pom中的命名未同步更改时,更改前的包名仍会出现在文件生成的选择界面,且会同时更改后和更改前的包同时生成,尽管大概率是pom中的包名称未更改的原因.

**Comment by makejavas** [comment]
意思是新包名与旧包名会同时生成文件？

**Comment by x-chuiao** [comment]
是的

**Comment by makejavas** [comment]
你是在生成界面忘记修改包名了吧，我测试了好几遍都没出现你说的情况。

**Comment by x-chuiao** [comment]
pom.xml文件中包名未更改,仍为com.***:
![image](https://user-images.githubusercontent.com/37545780/85195477-6ccffd80-b305-11ea-9ca8-d083b649c07a.png)
生成测试:
![20200620_144326](https://user-images.githubusercontent.com/37545780/85195472-5d50b480-b305-11ea-8af7-cd10a19a68a2.gif)

**Comment by x-chuiao** [comment]
我知道pom不更改对应的包名很愚蠢,但是也许能给插件的优化有些许帮助

**Comment by makejavas** [comment]
[试试内测版](http://www.shujuhaiyang.com/)

**Comment by makejavas** [comment]
该问题已经长时间没有回复，暂时关闭，如任然存在可再次打开。
