### ISSUE TITLE
添加的类型转换问题

### ISSUE THREAD

**Issue by tonycody** [makejavas/EasyCode#4]
你好：
tinyint(\(\d+\))?
你试着添加一下这个类型，msyql的。然后根据表生成一下java实体。你试试有没有问题，我自己试了。类型不会转换，总是Object

**Comment by tonycody** [comment]
另外建议，生成的注释为javadoc，行注释感觉太奇怪了

**Comment by tonycody** [comment]
虽然可以自定义，建议默认就是javadoc

**Comment by makejavas** [comment]
感谢你的建议，后期改进。

**Comment by makejavas** [comment]
新版本已改进，已发布，待推送。
