### ISSUE TITLE
生成代码 Path 不对问题

### ISSUE THREAD

**Issue by poazy** [makejavas/EasyCode#41]
E:/projects/xxx/xxx
E:/projects/xxx/xxx-service
E:/projects/xxx/xxx-api

1、E:/projects/xxx/xxx 为 .idea目录 所在目录
2、用 EasyCode 1.2.4RC2 生成代码时 Path 选择的是 E:/projects/xxx/xxx-service/src/main/java/com/aaa/dawo/service 路径
	生成的代码放到 E:/projects/xxx/xxx/-service/src/main/java/com/aaa/dawo/service 路径下了
	再看生成代码对话框中的 Path 值为 .-service/src/main/java/com/aaa/dawo/service
	EasyCode 1.2.4RC2 是不是对路径作了替换处理
        将 `E:/projects/xxx/xxx-service` 中的 `E:/projects/xxx/xxx` 替换掉为 `.` 了
        这样导致生成的代码不在指定的目录下的问题
3、之前用 EasyCode 1.2.3 时没有这个问题

**Comment by makejavas** [comment]
问题已修复，[查看](https://github.com/makejavas/EasyCode/commit/019b0067a3c851efd7de1ce259f88f0e1fc43cb8)

**Comment by poazy** [comment]
> 问题已修复，[查看](https://github.com/makejavas/EasyCode/commit/6c1e82d6e088e0dc8eef9e04d274ad59b2196fb5)

什么时候发布版本 RC3 来试试?

**Comment by makejavas** [comment]
内测版已发布，[下载地址](http://www.shujuhaiyang.com/)

**Comment by poazy** [comment]
> 内测版已发布，[下载地址](http://www.shujuhaiyang.com/)

试了下 RC3 版本，可以了。<br/> 但是生成后再次生成查看对话框中的 Path 时，发现 Path 的值还是 `.-service/src/main/java/com/aaa/dawo/service`，对话框显示的 Path 值还是有问题

**Comment by makejavas** [comment]
已经进行修复，试试再下载一次

**Comment by poazy** [comment]
> 已经进行修复，试试再下载一次

可以了。谢谢！
