### ISSUE TITLE
1.2.4版本，大量表生成时，removePre属性不生效

### ISSUE THREAD

**Issue by zbolun** [makejavas/EasyCode#44]

**Comment by makejavas** [comment]
经测试，未发现该问题。麻烦提供相关信息。

**Comment by btboys** [comment]
> 经测试，未发现该问题。麻烦提供相关信息。

多选表生成代码时，如果修改了配置，生成的EasyCodeConfig只会更新第一个。这个和removePre不生效是一致的，都出现在多选表的情况下。单表选择生成代码没有问题。

**Comment by makejavas** [comment]
在没有勾选统一配置的情况下，当前的配置不会对所有表生效，意味着你的其他表并没有配置表前缀。

**Comment by zbolun** [comment]
> 在没有勾选统一配置的情况下，当前的配置不会对所有表生效，意味着你的其他表并没有配置表前缀。

懂了。我对配置理解不清晰。
