### ISSUE TITLE
去除表前缀if写的没毛病，内部替换字符串的有问题，应该从首字符替换，不应该直接全tableName进行replace

### ISSUE THREAD

**Issue by zbolun** [makejavas/EasyCode#45]
![image](https://user-images.githubusercontent.com/13815505/88544290-c1287480-d04b-11ea-9ffd-e481d897ef39.png)
r_user_role, 输入前缀 r_ ,替换后为 userole
输入前缀 r   替换后为  _use_ole

**Comment by makejavas** [comment]
已修复，[查看提交](https://github.com/makejavas/EasyCode/commit/95517aff34d972805938665c8432bebba01e06f4)，(下载最新版本)[http://www.shujuhaiyang.com/](内测版本)
