### ISSUE TITLE
和MybatisX的兼容性：mysql环境下能不能在mapper.xml里把数据库名用变音符(`)圈起来呢？

### ISSUE THREAD

**Issue by peter17ji** [makejavas/EasyCode#46]
MybatisX是Mybatis Plus作者的IDEA下mapper.xml高亮和语法检查插件（https://gitee.com/baomidou/MybatisX/attach_files），但对于库名有减号(-)的mysql数据库，Easy Code生成的mapper.xml无法正确高亮。
![屏幕截图(41)](https://user-images.githubusercontent.com/29380055/88878423-89dbe280-d25a-11ea-8962-09771fae2348.png)
直接在模板里加变音符显然很可能会破坏和其他种类数据库的兼容性，所以希望作者能给mysql数据源单独做处理，把数据库名用变音符(`)圈起来。
![屏幕截图(42)](https://user-images.githubusercontent.com/29380055/88878786-3c13aa00-d25b-11ea-88ff-cab02fbd1b05.png)

**Comment by anjia0532** [comment]
你可以自定义模板

**Comment by makejavas** [comment]
暂时先关闭该issues，如问题依然存在请重新打开。
