### ISSUE TITLE
数据表前缀移除失效

### ISSUE THREAD

**Issue by RGaius** [makejavas/EasyCode#54]
## 插件版本

1.2.4-RC3

## 操作步骤

我选择了三个表进行代码生成并统一配置，最终只有第一个表移除了表前缀，后续两个前缀依然被保留
![image](https://user-images.githubusercontent.com/19511826/96701580-59bc5f80-13c3-11eb-89cc-092138515a09.png)
![image](https://user-images.githubusercontent.com/19511826/96702034-e830e100-13c3-11eb-8fab-b80a9d60d70b.png)

**Comment by ruby-ya** [comment]
在全局变量里添加对$tableInfo.name的修改，批量去除前缀。给每个模板引入这个全局配置

**Comment by Ero98** [comment]
暂时的解决办法是init里添加修改$tableInfo.name的代码，如去除“t_”前缀：
```
##去掉表的t_前缀
##这个插件处理的第一个表覆盖了这里处理过的表名，后面的表却不受影响
#if($tableInfo.obj.name.startsWith("t_"))
    $!tableInfo.setName($tool.getClassName($tableInfo.obj.name.substring(2)))
#end
```
同时在生成类时填写“RemovePre”，如`t_`。
我觉得这是一个bug

**Comment by makejavas** [comment]
RemovePre 确实只能去除第一张表的前缀，目前已经修复，尚未发布。

**Comment by makejavas** [comment]
请升级至最新版解决，暂时先关闭问题。如问题仍然存在请重新打开。
