### ISSUE TITLE
大小写不敏感问题

### ISSUE THREAD

**Issue by jilliss** [makejavas/EasyCode#58]
![image](https://user-images.githubusercontent.com/30598952/102854112-c7851600-445c-11eb-885f-89d98aa15e7f.png)
![image](https://user-images.githubusercontent.com/30598952/102854140-d5d33200-445c-11eb-8ae8-a4739edd0150.png)

现在只能手动修改

**Comment by makejavas** [comment]
请使用column.obj.name
