### ISSUE TITLE
全局变量无效

### ISSUE THREAD

**Issue by shaokuuipo** [makejavas/EasyCode#59]
在全局变量中设置
##去掉表的t_前缀
$!tableInfo.setName($tool.getClassName($tableInfo.obj.name.replaceFirst("started_","")))

在模板中调用 $!{tableInfo.name}
生成的代码中任然包含started
版本：1.2.4-RC3

**Comment by pansong291** [comment]
如果你的全局变量设置在 `init` 里面，则需要先调用 `$!init` ，如果你的全局变量设置在 `define` 里面，则需要先调用 `$!define` 。

**Comment by makejavas** [comment]
暂时先关闭该issues，如问题依然存在请重新打开。
