### ISSUE TITLE
array类型

### ISSUE THREAD

**Issue by sdwujt** [makejavas/EasyCode#6]
数据库是postgresql 类型是array
![image](https://user-images.githubusercontent.com/24410220/58546972-147d1800-8239-11e9-9c41-be9a1546a4a4.png)
type mapper 配置
![image](https://user-images.githubusercontent.com/24410220/58546326-b00d8900-8237-11e9-807e-2fac7e38e180.png)
生成模板报错
![image](https://user-images.githubusercontent.com/24410220/58546380-cb789400-8237-11e9-913c-ea90b4ad174c.png)

请问是type mapper配置错了吗？

**Comment by makejavas** [comment]
注意正则表达转移字符，\[\]
