### ISSUE TITLE
能不能将自定义的配置导出到本地保存，不止是上传

### ISSUE THREAD

**Issue by pansong291** [makejavas/EasyCode#63]
请问作者有意向实现此功能吗？谢谢答复

**Comment by Naratsuna** [comment]
这作者他妈就是个脑瘫，傻逼导出功能还不如不做，网站做成那副吊样好意思让人用

**Comment by makejavas** [comment]
感谢您的建议，我们会进行改进升级！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "makejavas/EasyCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月9日(星期五) 下午3:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [makejavas/EasyCode] 能不能将自定义的配置导出到本地保存，不止是上传 (#63)





 
这作者他妈就是个脑瘫，傻逼导出功能还不如不做，网站做成那副吊样好意思让人用

**Comment by makejavas** [comment]
已解决！
