### ISSUE TITLE
希望提供字符串替换的工具

### ISSUE THREAD

**Issue by deanjoson** [makejavas/EasyCode#68]
项目严格按照阿里巴巴的《Java开发手册-泰山版》进行开发的。在文档中有一条规则如下
![image](https://user-images.githubusercontent.com/4687434/117534520-5bc6d280-b024-11eb-9c8a-a0b9c194b232.png)
也就是在转换字段至实体的时候需要将前缀is替换为空串。目前插件没有替换的工具类。本人已经通过下载源码调整使用，希望官方插件也能包含该功能。

```
 // NameUtils 类中增加如下方法
    /**
     * 名称字符串替换
     *
     * @param str  原始字符串
     * @param str1 需要被替换的字符串
     * @param str2 需要替换换为的字符串
     * @return
     */
    public String replace(String str, String str1, String str2) {
        return str.replace(str1, str2);
    }
```

**Comment by makejavas** [comment]
不需要提供工具，直接使用java.lang.String.replace方法即可。
例如${column.name.replace("get", "is")}
