### ISSUE TITLE
无法通过 column.obj.notNull 获取到列是否非空信息。

### ISSUE THREAD

**Issue by JL-Code** [makejavas/EasyCode#69]
如图所示：无法通过 column的 obj 原始对象获取到 notNull 属性的值！这与 Wiki文档上说明的通过 notNull 获取不一致。
![image](https://user-images.githubusercontent.com/14163944/120478255-3b99f180-c3df-11eb-8dea-1cf77a0dd6e0.png)

期望能获取到 column 的是否必填的信息

**Comment by makejavas** [comment]
请使用column.obj.isNotNull()
