### ISSUE TITLE
webstorm2021.2.1 easycode 1.2.4-RELEASE出现 java.lang.NoClassDefFoundError: com/intellij/psi/PsiClass

### ISSUE THREAD

**Issue by theoly** [makejavas/EasyCode#72]
webstorm 2021.2.1,
1.2.4RC4没问题

**Comment by makejavas** [comment]
应该是添加了通过Java实体类生成代码导致的

**Comment by makejavas** [comment]
这是个兼容性问题，我改进一下

**Comment by makejavas** [comment]
升级到[Easy Code 1.2.5-RELEASE](https://plugins.jetbrains.com/plugin/10954-easy-code/versions/stable/136792)即可解决，注意不是Easy Code 1.2.5-java.RELEASE版本。
