### ISSUE TITLE
模板中一些指令没法解析执行

### ISSUE THREAD

**Issue by a2020883119** [makejavas/EasyCode#73]
idea版本：
![image](https://user-images.githubusercontent.com/13160008/133365416-f979be79-c1c4-4c59-98cd-a745a6522279.png)
插件版本：
![image](https://user-images.githubusercontent.com/13160008/133365455-8ee6bc66-c035-49ce-aca9-dafa92edf8ff.png)

**xml中：
 #allSqlColumn()**
![image](https://user-images.githubusercontent.com/13160008/133365361-4764936b-ae24-4935-8d7f-ba916d6016b9.png)

**entity中：
#getSetMethod($column)**
![image](https://user-images.githubusercontent.com/13160008/133365328-85480360-3a66-4034-ab58-0015a3c99144.png)

**Comment by makejavas** [comment]
将模板上面的$!{define}  修改为 $!{define.vm}  注意要与Global Config同名。
