### ISSUE TITLE
实现动态排除列 setOtherColumn 不生效

### ISSUE THREAD

**Issue by russleung44** [makejavas/EasyCode#77]
动态排除列里 setOtherColumn 后在 template 里循环 ohterColumn 不生效

![动态排除1.png](https://i.loli.net/2021/10/20/J3sLpMD5SQoz2eN.png)

![动态排除2.png](https://i.loli.net/2021/10/20/cfgVBWHAsYt7RGZ.png)

**Comment by russleung44** [comment]
估计有缓存, 现在没问题了

**Comment by zjarlin** [comment]
请问动态排除列时,我并不知道父类的字段叫什么,我只希望已经extends 时忽略父类的字段生成,该如何全局配置呢
