### ISSUE TITLE
调用service方法，方法无法生成

### ISSUE THREAD

**Issue by haojiashi** [makejavas/EasyCode#8]
$!tool.firstLowerCase($tableInfo.name)Biz.updateSelectiveById($!tool.firstLowerCase($tableInfo.name))
生成出来的 只有baseTestBiz， 点以及后面的方法都不生成

**Comment by jasonli3179** [comment]
$!{tool.firstLowerCase($!tableInfo.name)}Biz.updateSelectiveById($!tool.firstLowerCase($tableInfo.name))

**Comment by jasonli3179** [comment]
要加上大括号，是这个脚本语言语法要求，不然它认为Biz后面的点和你之前调用$对象成员的点含义一样

**Comment by haojiashi** [comment]
好用，非常感谢
