### ISSUE TITLE
选择module能否支持关键词查询选择或按字母排序

### ISSUE THREAD

**Issue by fishwithwater** [makejavas/EasyCode#89]
生成代码时选择module的组件，能否支持输入关键词查询选择，或者按字母排序一下。现在应该是乱序的，项目有一百多个module，选择的时候眼睛都看花了😂

**Comment by makejavas** [comment]
![image](https://user-images.githubusercontent.com/18339862/177464151-650ce564-1974-4887-afcd-189f954f813a.png)

**Comment by makejavas** [comment]
@fishwithwater 代码已提交， 55f09db096296e5470ba73d696cda663d48a8890
