### ISSUE TITLE
mapper.xml模板，没有把 jdbcType生成

### ISSUE THREAD

**Issue by ztg-zlu** [makejavas/EasyCode#96]
<result property="$!column.name" column="$!column.obj.name" jdbcType="$!column.ext.jdbcType"/>

生成的jdbcType为空，应该怎么配置jdbcType
![image](https://user-images.githubusercontent.com/26703048/188098722-6d7b201b-69f2-4bd8-b61e-3c7cc196d3c9.png)

**Comment by ztg-zlu** [comment]
哦，找到原因了，少写了   $!{mybatisSupport.vm}

**Comment by i7lzz** [comment]
有用
