### ISSUE TITLE
怎么使生成的文件添加前缀

### ISSUE THREAD

**Issue by coolapker** [makejavas/EasyCode#97]
比如service.java文件，最后生成的是IService.java

**Comment by makejavas** [comment]
自行修改模板即可实现

**Comment by coolapker** [comment]
![image](https://user-images.githubusercontent.com/76961348/196917922-a23a6e7c-8fa2-4a79-85cb-3aef55e7d28d.png)
试了好长时间。最后生成的文件名和类名总是不一致，导致这样，求大佬指点迷津

**Comment by coolapker** [comment]
![image](https://user-images.githubusercontent.com/76961348/196918411-d69bee26-d003-4346-8d1a-a728dba2489f.png)
模版是这样设置的，类名前也加I了，还是没成功

**Comment by makejavas** [comment]
![image](https://user-images.githubusercontent.com/18339862/196920342-ce229c6e-a946-4b4b-9671-ac069114d6ff.png)

这个宏定义是这样的，你的用法不正确

你可以选择不适用宏定义，自行调回调方法
`
$!callback.setSavePath($tool.append($tableInfo.savePath,"/service"))
$!callback.setFileName($tool.append("I",$tableInfo.name, "Service.java"))
`

**Comment by coolapker** [comment]
谢谢大佬！成功了！
